swagger: '2.0'
info:
  description: "Documentação da API do projeto escola Comp."
  version: '1.0.0'
  title: 'Projeto'
basePath: '/api'
tags:
  - name: 'categoria'
    description: 'Operações relacionadas a categoria'
  - name: 'playlist'
    description: 'Operações relacionadas a playlist'
  - name: 'aula'
    description: 'Operações relacionadas a aula'
  - name: 'arquivos'
    description: 'Operações relacionadas a arquivos'
schemes:
  - 'https'
paths:
  /categoria:
    get:
      tags:
        - 'categoria'
      summary: 'Categorias'
      description: 'Retorna todas categorias'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'array'
            items:
              type: 'object'
              properties:
                playlists:
                  type: 'array'
                  example: []      
                _id:
                  type: 'string'
                nome:
                  type: 'string'
        '500':
          description: 'Erro ao listar categorias'
    post:
      tags:
        - 'categoria'
      summary: 'Postar Categoria'
      description: 'Postar categoria'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados de categoria'
          required: true
          schema:
            type: 'object'
            properties:
              playlists:
                type: 'array'
                example: []
              nome:
                type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '500':
          description: 'Erro interno de servidor'
  
  /categoria/{name}:
    get:
      tags:
        - 'categoria'
      summary: 'Categoria'
      description: 'Retorna categoria especificada'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: name
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'object'
            properties:
              playlists:
                type: 'array'
                example: [{'aulas':[], '_id':string, nome: string}]
              nome:
                type: 'string'
        '400':
          description: 'Faltando Informações necessárias'
        '404':
          description: 'Categoria nao encontrada'
  /categoria/{id}:
    put:
      tags:
        - 'categoria'
      summary: 'Postar Categoria'
      description: 'Postar categoria'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Dados de categoria'
          required: true
          schema:
            type: 'object'
            properties:
              playlists:
                type: 'array'
                example: []
              nome:
                type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '404':
          description: 'Categoria nao encontrada'
        '500':
          description: 'Erro interno de servidor'
    delete:
      tags:
        - 'categoria'
      summary: 'Deleta a categoria'
      description: 'Deleta a categoria. Requer nível Admin.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '404':
          description: 'Categoria nao encontrada'
        '500':
          description: 'Erro interno de servidor'


          
  /categoria/{id}/playlist:
    post:
      tags:
        - 'categoria'
      summary: 'Postar playlist'
      description: 'Postar playlist'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
        - in: 'body'
          name: 'body'
          description: 'Dados de playlist'
          required: true
          schema:
            type: 'object'
            properties:
              aulas:
                type: 'array'
                example: []
              nome:
                type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '404':
          description: 'Categoria nao encontrada'
        '500':
          description: 'Erro interno de servidor'
  
  /playlist/{id}:
    get:
      tags:
        - 'playlist'
      summary: 'Playlist'
      description: 'Retorna playlist especificada'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'object'
            properties:
              aulas:
                type: 'array'
                example: [{'_id':string, nome: string, link: string}]
              nome:
                type: 'string'
        '400':
          description: 'Faltando Informações necessárias'
        '404':
          description: 'Categoria nao encontrada'
    put:
      tags:
        - 'playlist'
      summary: 'Editar Playlist'
      description: 'Editar Playlist'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
        - in: 'body'
          name: 'body'
          description: 'Dados de playlist'
          required: true
          schema:
            type: 'object'
            properties:
              aulas:
                type: 'array'
                example: []
              nome:
                type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '404':
          description: 'Categoria nao encontrada'
        '500':
          description: 'Erro interno de servidor'
    delete:
      tags:
        - 'playlist'
      summary: 'Deleta a Playlist'
      description: 'Deleta a Playlist. Requer nível Admin.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '404':
          description: 'Playlist nao encontrada'
        '500':
          description: 'Erro interno de servidor'

  /playlist/{id}/aula:
    post:
      tags:
        - 'playlist'
      summary: 'Postar aula'
      description: 'Postar aula'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
        - in: 'body'
          name: 'body'
          description: 'Dados de playlist'
          required: true
          schema:
            type: 'object'
            properties:
              link:
                type: 'string'
              nome:
                type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '404':
          description: 'Playlist nao encontrada'
        '500':
          description: 'Erro interno de servidor'
  /playlist/{id}/aula/{idAula}:
    delete:
      tags:
        - 'playlist'
      summary: 'Deleta a Aula'
      description: 'Deleta a Aula. Requer nível Admin.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
        - in: 'path'
          name: idAula
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '404':
          description: 'Aula nao encontrada'
        '500':
          description: 'Erro interno de servidor'
  
  /aula/{id}:
    put:
      tags:
        - 'aula'
      summary: 'Editar aula'
      description: 'Editar aula'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
        - in: 'body'
          name: 'body'
          description: 'Dados de playlist'
          required: true
          schema:
            type: 'object'
            properties:
              link:
                type: 'string'
              nome:
                type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '404':
          description: 'Aula nao encontrada'
        '500':
          description: 'Erro interno de servidor'
    
  
  /arquivo:
    get:
      tags:
        - 'arquivos'
      summary: 'Arquivos'
      description: 'Retorna todos arquivos'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Deu tudo certo'
          schema:
            type: 'array'
            items:
              type: 'object'
              properties:
                nome:
                  type: 'string'  
                _id:
                  type: 'string'
                arquivo:
                  type: 'string'
        '500':
          description: 'Erro ao listar categorias'
    post:
      tags:
        - 'arquivos'
      summary: 'Postar arquivo'
      description: 'Postar arquivo'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'formData'
          name: 'nome'
          required: true
          type: string
        - in: 'formData'
          name: 'arquivo'
          required: true
          type: file
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '500':
          description: 'Erro interno de servidor'
  
  /arquivo/{id}:
    delete:
      tags:
        - 'arquivos'
      summary: 'Excluir arquivo'
      description: 'Excluir arquivo'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'path'
          name: id
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Deu tudo certo'
        '400':
          description: 'Faltou dados'
        '404':
          description: 'Aula nao encontrada'
        '500':
          description: 'Erro interno de servidor'






